version: '3'

services:
  msr14-mongo:
    container_name: msr14-mongo
    build: .
    ports:
      - "27017:27017"
    volumes:
      - ./mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
    # network_mode: host
    command:
    - "/bin/bash"
    - "-c"
    - "mongod --replSet=rs0"
    # - "mongorestore -d msr14 dump/msr14"
