version: '3.9'

services:
  msr14-mongo:
    container_name: msr14-mongo
    build: .
    ports:
      - "27017:27017"
    network_mode: host
    command:
    - "/bin/sh"
    - "-c"
    - "mongod --replSet=rs0"
