version: "3.9"
services:
  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    network_mode: host
    container_name: spark-worker-1
    ports:
      - 28081:28081
    environment:
      - SPARK_MASTER=spark://10.123.252.251:17077
      - SPARK_WORKER_PORT=28081
