version: "3.9"
services:
  datanode-1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode-1
    restart: always
    network_mode: host
    volumes:
      - hadoop_datanode-1:/hadoop/dfs/data
#    ports:
#      - 9864:9864
#      - 9866:9866
#      - 50010:50010
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env

  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    network_mode: host
#    ports:
#      - 18080:18080
#      - 17077:17077
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - SPARK_MASTER_PORT=17077
      - SPARK_MASTER_WEBUI_PORT=18080

volumes:
  hadoop_datanode-1: