version: "3.9"
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    network_mode: host
    restart: always
#    ports:
#      - 9870:9870
#      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=groupfive
    env_file:
      - ./hadoop.env

  datanode-2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode-2
    restart: always
    network_mode: host
    volumes:
      - hadoop_datanode-2:/hadoop/dfs/data
#    ports:
#      - 9864:9864
#      - 9866:9866
#      - 50010:50010
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env

  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    network_mode: host
#    ports:
#      - 28081:28081
    environment:
      - SPARK_MASTER=spark://spark-master:17077
      - SPARK_LOCAL_IP=10.123.252.193
      - SPARK_WORKER_PORT=28081

volumes:
  hadoop_namenode:
  hadoop_datanode-2: