version: "3.9"
services:
  zk-2:
    image: confluentinc/cp-zookeeper:7.2.2
    network_mode: host
    container_name: zk-2
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: "10.123.252.251:12888:13888;10.123.252.213:22888:23888;10.123.252.193:32888:33888"
  kafka-2:
    image: confluentinc/cp-kafka:7.2.2
    network_mode: host
    container_name: kafka-2
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 10.123.252.251:12181,10.123.252.213:22181,10.123.252.193:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.123.252.213:29092