version: "3.9"
services: 
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    command: ["--replSet", "rs0"]
    ports:
      - 27017:27017
    volumes:
      - ./init.js:/docker-entrypoint-initdb.d/init.js