version: "3.9"
services:
  zk-2:
    image: confluentinc/cp-zookeeper:7.2.2
    network_mode: host
    container_name: zk-2
    volumes:
      - zk-2_data:/var/lib/zookeeper/data
      - zk-2_log:/var/lib/zookeeper/log
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: "zk-1:12888:13888;zk-2:22888:23888;zk-3:32888:33888"

  kafka-2:
    image: confluentinc/cp-kafka:7.2.2
    network_mode: host
    container_name: kafka-2
    volumes:
      - kafka-2_data:/var/lib/kafka/data
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zk-1:12181,zk-2:22181,zk-3:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:29092

volumes:
  zk-2_data:
  zk-2_log:
  kafka-2_data: